-- Supabase RLS'yi tüm mevcut tablolardan devre dışı bırak
-- Bu migration development/test ortamları için RLS'yi kapatır

-- Ana tablolar için RLS'yi devre dışı bırak
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE dreams DISABLE ROW LEVEL SECURITY;
ALTER TABLE comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE ads DISABLE ROW LEVEL SECURITY;
ALTER TABLE content_calendar DISABLE ROW LEVEL SECURITY;

-- İlişkisel tablolar için RLS'yi devre dışı bırak
ALTER TABLE dream_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE favorites DISABLE ROW LEVEL SECURITY;
ALTER TABLE view_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE comment_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE comment_reactions DISABLE ROW LEVEL SECURITY;

-- Blog tabloları için RLS'yi devre dışı bırak
ALTER TABLE blog_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_comment_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_subscribers DISABLE ROW LEVEL SECURITY;

-- Kullanıcı deneyimi tabloları için RLS'yi devre dışı bırak
ALTER TABLE user_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences DISABLE ROW LEVEL SECURITY;

-- Diğer özellik tabloları için RLS'yi devre dışı bırak
ALTER TABLE dream_journal DISABLE ROW LEVEL SECURITY;
ALTER TABLE search_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_polls DISABLE ROW LEVEL SECURITY;
ALTER TABLE poll_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE trending_themes DISABLE ROW LEVEL SECURITY;
ALTER TABLE dream_symbols DISABLE ROW LEVEL SECURITY;
ALTER TABLE cultural_interpretations DISABLE ROW LEVEL SECURITY;
ALTER TABLE ottoman_interpretations DISABLE ROW LEVEL SECURITY;
ALTER TABLE sleep_quality DISABLE ROW LEVEL SECURITY;
ALTER TABLE consultants DISABLE ROW LEVEL SECURITY;
ALTER TABLE appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE sponsored_content DISABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_summaries DISABLE ROW LEVEL SECURITY;
ALTER TABLE ab_tests DISABLE ROW LEVEL SECURITY;
ALTER TABLE ab_test_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE dream_locations DISABLE ROW LEVEL SECURITY;