// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from '@/lib/config';

if (!SUPABASE_URL || SUPABASE_URL.trim() === '') {
  throw new Error('VITE_SUPABASE_URL ortam değişkeni tanımlı değil.');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.trim() === '') {
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY ortam değişkeni tanımlı değil.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
